name: CI Test 

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build-type: [Release]

    runs-on: ${{ matrix.os }}
    
    env:
      INSTALL_DIR: ${{ github.workspace }}/install/
      
    steps:
      - name: Perform checkout
        uses: actions/checkout@v2

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libboost-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install boost

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: lukka/run-vcpkg@main
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgTriplet: x64-windows
          vcpkgArguments: 'boost-test'
          vcpkgGitCommitId: '30124253eecff36bc90f73341edbfb4f845e2a1e'
                    
      - name: Build (Non-Windows)
        if: runner.os != 'Windows'
        run: |
            mkdir -p build && cd build
            cmake .. -DBUILD_TESTING=TRUE -DCMAKE_BUILD_TYPE=${{ matrix.os }} -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
            cmake --build . --config ${{ matrix.build-type }} --target install

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
            mkdir -p build && cd build
            cmake .. -A x64 -DBUILD_TESTING=TRUE -DCMAKE_BUILD_TYPE=${{ matrix.os }} -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows
            cmake --build . --config ${{ matrix.build-type }} --target install

      - name: Test
        run: |
            cd build
            ctest -C Release
